### ISSUE TITLE
How to evaluate dreamer

### ISSUE THREAD

**Issue by Jiankai-Sun** [google-research/dreamer#10]
Hi, @danijar,

This work is quite interesting!

Is there a separate script we can use to load the trained model+policy/model/policy and evaluate the performance of Dreamer? At present, it seems that we can only test while training, alternating. It's not easy to deploy a model. It seems that the flags `--resume_runs True` can not achieve the desired function.

Thank you.

**Comment by danijar** [comment]
Thanks for your question. There is no flag for evaluation without training at the moment. It should be easy to disable the training step in the code though, and you could add a flag for it.
