### ISSUE TITLE
Generating performance curves of Figure 7 (Dream to Control)

### ISSUE THREAD

**Issue by curiousgeorgie** [google-research/dreamer#5]
Thanks a lot for providing this great open source implementation of Dreamer!
Does running the following sample command generate the Dreamer performance curve provided in Figure 7 of the paper?

`python3 -m dreamer.scripts.train --logdir ./logdir/control  --params '{defaults: [dreamer], tasks: [walker_run]}'`

Running for a little over 1.3M steps on 2 seeds the generated curve in (...)/trainer/test/score seems to follow the performance of PlaNet in Figure 7. Am I comparing the right curves and setting the proper parameters? Thanks a lot!

**Comment by danijar** [comment]
Yes -- maybe you're looking at train instead of eval curves (i.e. without added action noise)?

**Comment by curiousgeorgie** [comment]
I think this might be resolved: would it be correct to say that the performance curves on TensorBoard for e.g. DM Control tasks need to be re-scaled in X by 1/5 (1000 steps per episode assuming no early termination / 5000 global steps (100 gradient steps x 50 batch size)) to correspond to the curves in the paper? Thanks a lot!

**Comment by danijar** [comment]
Yes, that's correct.
